atlas_homepage:
    pattern:  /
    defaults: { _controller: AtlasFrontEndBundle:Page:home }

atlas_aims_and_objectives:
    pattern:  /aims-and-objectives
    defaults: { _controller: AtlasFrontEndBundle:Page:aimsAndObjectives }

atlas_our_operations:
    pattern:  /our-operations
    defaults: { _controller: AtlasFrontEndBundle:Page:ourOperations }

atlas_contacts:
    pattern:  /contacts
    defaults: { _controller: AtlasFrontEndBundle:Page:contacts }

atlas_privacy_policy:
    pattern:  /privacy
    defaults: { _controller: AtlasFrontEndBundle:Page:privacy }

atlas_terms:
    pattern:  /terms
    defaults: { _controller: AtlasFrontEndBundle:Page:terms }

atlas_important_notice:
    pattern:  /important-notice
    defaults: { _controller: AtlasFrontEndBundle:Page:importantNotice }

atlas_risk_warning:
    pattern:  /risk-warning
    defaults: { _controller: AtlasFrontEndBundle:Page:riskWarning }    